apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: inventory-system
spec:
  selector:
    app: inventory-service
  ports:
    - name: http
      port: 2001
      targetPort: 2001
  type: ClusterIP
